### ISSUE TITLE
problem with the new GPUs

### ISSUE THREAD

**Issue by youyeg** [fuy34/superpixel_fcn#25]
I have tried to install the requirements via conda, so it will check the requirements' compatibilities.
I get this error, which I searched and I found out, it's due to CUDA error. The new GPUs don't work with CUDA 9, and it's required to either compile torch 0.4.1 from source with CUDA 10, or install higher version of torch, which doesn't work with your code. Also, you didn't mention the torchvision version, but luckily conda would find the proper version(0.2.1). Could you please update your code for python 3+ and recent torch version?:
```THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "run_demo.py", line 169, in <module>
    main()
  File "run_demo.py", line 164, in main
    time = test(args, model, tst_lst, save_path, n)
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 46, in decorate_no_grad
    return func(*args, **kwargs)
  File "run_demo.py", line 97, in test
    output = model(img1.cuda().unsqueeze(0))
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yousef/Desktop/SpixelFCN/python3-version/superpixel_fcn/models/Spixel_single_layer.py", line 65, in forward
    out1 = self.conv0b(self.conv0a(x)) #5*5
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yousef/anaconda3/envs/superpix_py36/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663```

**Comment by fuy34** [comment]
Which torch version are you using? 

I have successfully run everything on python 3.6, torch 1.2, and CUDA 10 before. For the newer version, I am not sure.  My torchvision version follows the official pair on the PyTorch website.  The information in issue #13 may be helpful for you as well. 

Another alternative is to simply run everything on CPU if you do not need to train the model.
